import turtle
sc=turtle.Screen()
sc.setup(500,500)
sc.bgcolor("Red")
board=turtle.Turtle()
sc.title("This is Turtle")
turtle.fillcolor("White")
turtle.color("Turquoise")
turtle.begin_fill()
turtle.circle(60)
board.forward(100)
board.right(90)
board.forward(100)
board.right(90)
board.forward(100)
board.right(90)
board.forward(100)
turtle.end_fill()
turtle.done()
